In [360]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

In [361]:
dataset = './datasets/titanic_train.csv'
titanic = pd.read_csv(dataset)
titanic.head()

passenger_id  pclass                                               name  \
0          1216       3                                 Smyth, Miss. Julia   
1           699       3                                    Cacic, Mr. Luka   
2          1267       3  Van Impe, Mrs. Jean Baptiste (Rosalie Paula Go...   
3           449       2              Hocking, Mrs. Elizabeth (Eliza Needs)   
4           576       2                                    Veal, Mr. James   

      sex   age  sibsp  parch  ticket     fare cabin embarked boat  body  \
0  female   NaN      0      0  335432   7.7333   NaN        Q   13   NaN   
1    male  38.0      0      0  315089   8.6625   NaN        S  NaN   NaN   
2  female  30.0      1      1  345773  24.1500   NaN        S  NaN   NaN   
3  female  54.0      1      3   29105  23.0000   NaN        S    4   NaN   
4    male  40.0      0      0   28221  13.0000   NaN        S  NaN   NaN   

                  home.dest  survived  
0                       NaN         1  
1                   Croatia         0  
2                       NaN         0  
3      Cornwall / Akron, OH         1  
4  Barre, Co Washington, VT         0

In [362]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 850 entries, 0 to 849
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   passenger_id  850 non-null    int64  
 1   pclass        850 non-null    int64  
 2   name          850 non-null    object 
 3   sex           850 non-null    object 
 4   age           676 non-null    float64
 5   sibsp         850 non-null    int64  
 6   parch         850 non-null    int64  
 7   ticket        850 non-null    object 
 8   fare          849 non-null    float64
 9   cabin         191 non-null    object 
 10  embarked      849 non-null    object 
 11  boat          308 non-null    object 
 12  body          73 non-null     float64
 13  home.dest     464 non-null    object 
 14  survived      850 non-null    int64  
dtypes: float64(3), int64(5), object(7)
memory usage: 99.7+ KB


In [363]:
titanic.describe().round(2)

passenger_id  pclass     age   sibsp   parch    fare    body  survived
count        850.00  850.00  676.00  850.00  850.00  849.00   73.00    850.00
mean         662.82    2.32   29.52    0.52    0.38   34.01  165.82      0.37
std          380.75    0.84   14.56    1.11    0.88   53.71   99.07      0.48
min            1.00    1.00    0.17    0.00    0.00    0.00    4.00      0.00
25%          332.25    2.00   20.00    0.00    0.00    7.90   75.00      0.00
50%          676.50    3.00   28.00    0.00    0.00   14.11  166.00      0.00
75%          992.25    3.00   37.00    1.00    0.00   31.00  260.00      1.00
max         1307.00    3.00   80.00    8.00    9.00  512.33  328.00      1.00

In [364]:
titanic.isna().sum()

passenger_id      0
pclass            0
name              0
sex               0
age             174
sibsp             0
parch             0
ticket            0
fare              1
cabin           659
embarked          1
boat            542
body            777
home.dest       386
survived          0
dtype: int64

In [406]:
titanic.corr().round(2)

passenger_id  pclass   age  sibsp  parch  fare  body  survived
passenger_id          1.00    0.90 -0.34   0.10  -0.00 -0.48 -0.03     -0.31
pclass                0.90    1.00 -0.41   0.07  -0.01 -0.56 -0.09     -0.33
age                  -0.34   -0.41  1.00  -0.25  -0.16  0.19  0.17     -0.04
sibsp                 0.10    0.07 -0.25   1.00   0.39  0.14 -0.12     -0.04
parch                -0.00   -0.01 -0.16   0.39   1.00  0.25  0.13      0.06
fare                 -0.48   -0.56  0.19   0.14   0.25  1.00 -0.08      0.25
body                 -0.03   -0.09  0.17  -0.12   0.13 -0.08  1.00       NaN
survived             -0.31   -0.33 -0.04  -0.04   0.06  0.25   NaN      1.00

In [366]:
labels = ['pclass', 'sex', 'age', 'embarked', 'fare', "sibsp"]

In [367]:
titanic[labels]

pclass     sex   age embarked     fare  sibsp
0         3  female   NaN        Q   7.7333      0
1         3    male  38.0        S   8.6625      0
2         3  female  30.0        S  24.1500      1
3         2  female  54.0        S  23.0000      1
4         2    male  40.0        S  13.0000      0
..      ...     ...   ...      ...      ...    ...
845       1    male  55.0        S  50.0000      0
846       1    male  58.0        C  29.7000      0
847       2  female  24.0        S  26.0000      1
848       3  female   3.0        S  13.7750      1
849       2    male  52.0        S  13.0000      0

[850 rows x 6 columns]

In [368]:
X = titanic[labels]
y = titanic['survived']

In [369]:
y

0      1
1      0
2      0
3      1
4      0
      ..
845    0
846    0
847    1
848    0
849    0
Name: survived, Length: 850, dtype: int64

In [370]:
X.isna().sum()

pclass        0
sex           0
age         174
embarked      1
fare          1
sibsp         0
dtype: int64

In [371]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1,3])], remainder= 'passthrough')
Xtrans = np.array(ct.fit_transform(X))
Xtrans

array([[ 1.    ,  0.    ,  0.    , ...,     nan,  7.7333,  0.    ],
       [ 0.    ,  1.    ,  0.    , ..., 38.    ,  8.6625,  0.    ],
       [ 1.    ,  0.    ,  0.    , ..., 30.    , 24.15  ,  1.    ],
       ...,
       [ 1.    ,  0.    ,  0.    , ..., 24.    , 26.    ,  1.    ],
       [ 1.    ,  0.    ,  0.    , ...,  3.    , 13.775 ,  1.    ],
       [ 0.    ,  1.    ,  0.    , ..., 52.    , 13.    ,  0.    ]])

In [372]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='median')
imputer.fit(Xtrans)


SimpleImputer(strategy='median')

In [373]:
imputer.statistics_

array([ 0.    ,  1.    ,  0.    ,  0.    ,  1.    ,  0.    ,  3.    ,
       28.    , 14.1083,  0.    ])

In [374]:
X = imputer.transform(Xtrans)
X

array([[ 1.    ,  0.    ,  0.    , ..., 28.    ,  7.7333,  0.    ],
       [ 0.    ,  1.    ,  0.    , ..., 38.    ,  8.6625,  0.    ],
       [ 1.    ,  0.    ,  0.    , ..., 30.    , 24.15  ,  1.    ],
       ...,
       [ 1.    ,  0.    ,  0.    , ..., 24.    , 26.    ,  1.    ],
       [ 1.    ,  0.    ,  0.    , ...,  3.    , 13.775 ,  1.    ],
       [ 0.    ,  1.    ,  0.    , ..., 52.    , 13.    ,  0.    ]])

In [375]:
from sklearn.preprocessing import StandardScaler 
sc = StandardScaler()
X = sc.fit_transform(X)
X

array([[ 1.35750115, -1.35750115, -0.51100645, ..., -0.09304062,
        -0.48942222, -0.46996259],
       [-0.73664763,  0.73664763, -0.51100645, ...,  0.67670089,
        -0.47210156, -0.46996259],
       [ 1.35750115, -1.35750115, -0.51100645, ...,  0.06090768,
        -0.18340826,  0.42974056],
       ...,
       [ 1.35750115, -1.35750115, -0.51100645, ..., -0.40093723,
        -0.1489235 ,  0.42974056],
       [ 1.35750115, -1.35750115, -0.51100645, ..., -2.01739441,
        -0.37680248,  0.42974056],
       [-0.73664763,  0.73664763, -0.51100645, ...,  1.75433901,
        -0.39124879, -0.46996259]])

In [376]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
lr = LogisticRegression(random_state=42)
lr.fit(X_train, y_train)

LogisticRegression(random_state=42)

In [377]:
y_predict = lr.predict(X_test)

In [378]:
from sklearn.metrics import f1_score, precision_score, recall_score, mean_squared_error, accuracy_score

print("f1 score:", f1_score(y_predict, y_test))
print("precision score:", precision_score(y_predict, y_test))
print("recall score:", recall_score(y_predict, y_test))
print("accuracy_score:", accuracy_score(y_predict, y_test))

f1 score: 0.6984126984126984
precision score: 0.6470588235294118
recall score: 0.7586206896551724
mean squared error: 0.2235294117647059
accuracy_score: 0.7764705882352941


In [429]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(random_state=42, max_depth=6)
dtc.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=6, random_state=42)

In [430]:
y_predtc = dtc.predict(X_test)


In [432]:
print("f1 score:", f1_score(y_predtc, y_test))
print("precision score:", precision_score(y_predtc, y_test))
print("recall score:", recall_score(y_predtc, y_test))
print("accuracy_score:", accuracy_score(y_predtc, y_test))

f1 score: 0.7758620689655172
precision score: 0.6617647058823529
recall score: 0.9375
accuracy_score: 0.8470588235294118


In [409]:
titanic_test = pd.read_csv('./datasets/titanic_test.csv')
X_testing = titanic_test[labels]
X_testing

pclass     sex   age embarked      fare  sibsp
0         1    male  17.0        C  110.8833      0
1         3    male   NaN        S   14.5000      0
2         1    male  31.0        S   52.0000      1
3         3    male  41.0        S    7.1250      0
4         3    male  21.0        S    7.8958      0
..      ...     ...   ...      ...       ...    ...
454       3    male   NaN        S    7.8958      0
455       2    male  23.0        S   13.0000      0
456       1  female   NaN        C  110.8833      0
457       2    male  16.0        S   10.5000      0
458       3  female  10.0        S   24.1500      0

[459 rows x 6 columns]